# Generated by Django 6.0.3 on 2026-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_alter_customorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='detail_level',
            field=models.CharField(choices=[('Simple', 'Simple (Minimal Details)'), ('Medium', 'Medium (Standard Inkwork)'), ('Detailed', 'Detailed (Intricate Mandala/Zentangle)')], default='Simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='size',
            field=models.CharField(choices=[('A5', 'A5 (Small)'), ('A4', 'A4 (Medium)'), ('A3', 'A3 (Large)')], default='A4', max_length=10),
        ),
    ]
