# Generated by Django 6.0.3 on 2026-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_customorder_detail_level_alter_customorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
