# Generated by Django 6.0.3 on 2026-03-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
