# Generated by Django 6.0.3 on 2026-03-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_order_payment_method_order_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
