# Generated by Django 6.0.3 on 2026-04-10 12:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_customorder_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_screenshot'),
        ),
    ]
