# Generated by Django 6.0.3 on 2026-04-23 12:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_alter_artwork_image_alter_order_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='reference_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='reference_image'),
        ),
    ]
