# Generated by Django 6.0.3 on 2026-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_customorder_estimated_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='budget',
        ),
        migrations.AlterField(
            model_name='customorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
