# Generated by Django 6.0.3 on 2026-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_remove_customorder_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('Mandala', 'Mandala'), ('Zentangle', 'Zentangle'), ('Doodle', 'Doodle'), ('Typography', 'Typography'), ('Craft', 'Craft')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='art_type',
            field=models.CharField(choices=[('Mandala', 'Mandala'), ('Zentangle', 'Zentangle'), ('Doodle', 'Doodle'), ('Typography', 'Typography'), ('Craft', 'Craft')], default='Mandala', max_length=50),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted (Awaiting Payment)'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
